// <auto-generated />
using System;
using LY.LlmPool.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LY.LlmPool.DataMigrations.Sqlite.Migrations.LlmDb
{
    [DbContext(typeof(LlmDbContext))]
    partial class LlmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.ActivityTrace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("FinishReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputMessagesJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAppCall")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsToolCall")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("McpServerName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputContent")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentSpanId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseModelId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerAddress")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpanId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("jsonb");

                    b.Property<float?>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<string>("ToolDataJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("ToolType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.HasIndex("ConversationId");

                    b.HasIndex("StartTime");

                    b.HasIndex("TraceId");

                    b.HasIndex("ConversationId", "StartTime");

                    b.ToTable("ActivityTraces");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.AgentMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlmAppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmPromptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LlmAppId");

                    b.HasIndex("LlmConfigId");

                    b.HasIndex("LlmPromptId");

                    b.ToTable("AgentMembers");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.ChatExecutionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_successful");

                    b.Property<int>("MessageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("message_count");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("RequestModel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_model");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("Summary")
                        .HasColumnType("jsonb")
                        .HasColumnName("summary");

                    b.Property<int>("ToolCallCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tool_call_count");

                    b.Property<int>("ToolCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tool_count");

                    b.Property<int>("TotalCharacters")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_characters");

                    b.Property<double?>("TotalDurationMs")
                        .HasColumnType("REAL")
                        .HasColumnName("total_duration_ms");

                    b.Property<double?>("TtfbMs")
                        .HasColumnType("REAL")
                        .HasColumnName("ttfb_ms");

                    b.HasKey("Id");

                    b.HasIndex("ModelName");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("StartTime");

                    b.ToTable("chat_execution_records");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.ChatExecutionTimelineNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<double>("DeltaMs")
                        .HasColumnType("REAL")
                        .HasColumnName("delta_ms");

                    b.Property<double>("ElapsedMs")
                        .HasColumnType("REAL")
                        .HasColumnName("elapsed_ms");

                    b.Property<string>("ExecutionRecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_record_id");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("node_type");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRecordId");

                    b.HasIndex("ExecutionRecordId", "Sequence");

                    b.ToTable("chat_execution_timeline_nodes");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlmConfigId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModelCallStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModelResponseEndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModelResponseStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCallId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestDataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("RequestReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ResponseDataJson")
                        .HasColumnType("jsonb");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("WaitTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("LlmConfigId");

                    b.HasIndex("ParentCallId");

                    b.HasIndex("RequestReceivedAt");

                    b.ToTable("EndpointCallRecords");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AppType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("app_type");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("EndpointId")
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LlmConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_config_id");

                    b.Property<string>("LlmPromptId")
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_prompt_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OrchestrationMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("orchestration_mode");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("LlmConfigId");

                    b.HasIndex("LlmPromptId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("llm_apps");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalHeadersJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("AdditionalParameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_parameters");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpoint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpointConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmConfigId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LlmConfigId");

                    b.HasIndex("EndpointId", "LlmConfigId")
                        .IsUnique();

                    b.ToTable("EndpointConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmModelType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultEndpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModelTypes");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmPrompt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ModelParameters")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_parameters");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("llm_prompts");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmPromptHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("BasedOnVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("based_on_version");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModelParameters")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_parameters");

                    b.Property<string>("PromptId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_id");

                    b.Property<string>("TestConfigsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("test_configs");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime");

                    b.HasIndex("PromptId");

                    b.ToTable("llm_prompt_history");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.McpServerConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Args")
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Env")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headers")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaCacheJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("McpServerConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.PromptTool", b =>
                {
                    b.Property<string>("PromptId")
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_id");

                    b.Property<string>("ToolId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_id");

                    b.Property<string>("ToolType")
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_type");

                    b.HasKey("PromptId", "ToolId", "ToolType");

                    b.ToTable("prompt_tools");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.AgentMember", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmApp", "LlmApp")
                        .WithMany("AgentMembers")
                        .HasForeignKey("LlmAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmConfig", "LlmConfig")
                        .WithMany()
                        .HasForeignKey("LlmConfigId");

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmPrompt", "LlmPrompt")
                        .WithMany()
                        .HasForeignKey("LlmPromptId");

                    b.Navigation("LlmApp");

                    b.Navigation("LlmConfig");

                    b.Navigation("LlmPrompt");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.ChatExecutionTimelineNode", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.ChatExecutionRecord", "ExecutionRecord")
                        .WithMany("TimelineNodes")
                        .HasForeignKey("ExecutionRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRecord");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmEndpoint", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmConfig", "LlmConfig")
                        .WithMany()
                        .HasForeignKey("LlmConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", "ParentCall")
                        .WithMany("ChildCalls")
                        .HasForeignKey("ParentCallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Endpoint");

                    b.Navigation("LlmConfig");

                    b.Navigation("ParentCall");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmApp", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmEndpoint", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId");

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmConfig", "LlmConfig")
                        .WithMany()
                        .HasForeignKey("LlmConfigId");

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmPrompt", "LlmPrompt")
                        .WithMany()
                        .HasForeignKey("LlmPromptId");

                    b.Navigation("Endpoint");

                    b.Navigation("LlmConfig");

                    b.Navigation("LlmPrompt");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmConfig", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmModelType", "ModelType")
                        .WithMany("Configs")
                        .HasForeignKey("ModelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelType");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpointConfig", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmEndpoint", "Endpoint")
                        .WithMany("EndpointConfigs")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmConfig", "LlmConfig")
                        .WithMany("EndpointConfigs")
                        .HasForeignKey("LlmConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");

                    b.Navigation("LlmConfig");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmPromptHistory", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmPrompt", "Prompt")
                        .WithMany()
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.PromptTool", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmPrompt", "Prompt")
                        .WithMany("PromptTools")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.ChatExecutionRecord", b =>
                {
                    b.Navigation("TimelineNodes");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", b =>
                {
                    b.Navigation("ChildCalls");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmApp", b =>
                {
                    b.Navigation("AgentMembers");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmConfig", b =>
                {
                    b.Navigation("EndpointConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpoint", b =>
                {
                    b.Navigation("EndpointConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmModelType", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmPrompt", b =>
                {
                    b.Navigation("PromptTools");
                });
#pragma warning restore 612, 618
        }
    }
}
