using Microsoft.Extensions.AI;
using System.Diagnostics;
using LY.LlmPool.Web.Services.Telemetry;

namespace LY.LlmPool.Web.Services.Decorators;

/// <summary>
/// DelegatingChatClient 用于在 ChatClient 调用开始时设置 ConversationId
/// 从 HttpContext 请求中提取或自动生成 ConversationId，并设置到当前 Activity
/// </summary>
public class ConversationIdInjectingChatClient : DelegatingChatClient
{
    private readonly ILogger<ConversationIdInjectingChatClient> _logger;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public ConversationIdInjectingChatClient(
        IChatClient innerClient,
        ILogger<ConversationIdInjectingChatClient> logger,
        IHttpContextAccessor httpContextAccessor)
        : base(innerClient)
    {
        _logger = logger;
        _httpContextAccessor = httpContextAccessor;
    }

    public override async Task<Microsoft.Extensions.AI.ChatResponse> GetResponseAsync(
        IEnumerable<ChatMessage> messages,
        ChatOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        // 🎯 在调用开始时设置 ConversationId
        InjectConversationId();

        return await base.GetResponseAsync(messages, options, cancellationToken);
    }

    public override async IAsyncEnumerable<ChatResponseUpdate> GetStreamingResponseAsync(
        IEnumerable<ChatMessage> messages,
        ChatOptions? options = null,
        [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        // 🎯 在调用开始时设置 ConversationId
        InjectConversationId();

        await foreach (var update in base.GetStreamingResponseAsync(messages, options, cancellationToken))
        {
            yield return update;
        }
    }

    /// <summary>
    /// 提取或生成 ConversationId 并设置到当前 Activity
    /// </summary>
    private void InjectConversationId()
    {
        var currentActivity = Activity.Current;
        if (currentActivity == null)
        {
            _logger.LogWarning("⚠️ ConversationIdInjectingChatClient: Activity.Current is NULL");
            return;
        }

        // 检查是否已经设置了 ConversationId（避免重复设置）
        var existingConvId = currentActivity.Tags.FirstOrDefault(t => t.Key == ActivityExtensions.GenAIConversationId).Value;
        if (!string.IsNullOrEmpty(existingConvId))
        {
            _logger.LogDebug("✅ ConversationId already set: {ConversationId}", existingConvId);
            return;
        }

        // 🎯 提取或生成 ConversationId
        var conversationId = ExtractConversationId();

        // 🎯 设置到当前 Activity
        currentActivity.AddTag(ActivityExtensions.GenAIConversationId, conversationId);

        _logger.LogInformation(
            "🔗 [ConversationId 设置] ChatClient 设置 ConversationId: {ConversationId} | Activity: {Name} | SpanId: {SpanId}",
            conversationId,
            currentActivity.OperationName,
            currentActivity.SpanId);
    }

    /// <summary>
    /// 提取或生成 ConversationId
    /// 优先级:
    /// 1. HTTP Header "X-Conversation-Id"
    /// 2. 请求 Body 中的 "conversation_id" (需要从 HttpContext 读取)
    /// 3. 自动生成 (格式: conv-auto-{traceid}-{guid})
    /// </summary>
    private string ExtractConversationId()
    {
        var httpContext = _httpContextAccessor.HttpContext;
        
        // 1. 尝试从 HTTP Header 提取
        if (httpContext != null && 
            httpContext.Request.Headers.TryGetValue("X-Conversation-Id", out var headerValue))
        {
            var conversationId = headerValue.ToString();
            if (!string.IsNullOrWhiteSpace(conversationId))
            {
                _logger.LogDebug("📥 ConversationId from Header: {ConversationId}", conversationId);
                return conversationId;
            }
        }

        // 2. 尝试从请求 Body 提取 (通过 Items 传递)
        if (httpContext?.Items.TryGetValue("ConversationId", out var bodyConvId) == true &&
            bodyConvId is string convIdStr &&
            !string.IsNullOrWhiteSpace(convIdStr))
        {
            _logger.LogDebug("📥 ConversationId from Body (via Items): {ConversationId}", convIdStr);
            return convIdStr;
        }

        // 3. 自动生成 ConversationId
        var traceId = Activity.Current?.TraceId.ToString() ?? Guid.NewGuid().ToString("N");
        var shortGuid = Guid.NewGuid().ToString("N").Substring(0, 8);
        var autoGeneratedId = $"conv-auto-{traceId.Substring(0, 8)}-{shortGuid}";

        _logger.LogDebug(
            "🔧 Auto-generated ConversationId: {ConversationId} (no client-provided ID)",
            autoGeneratedId);

        return autoGeneratedId;
    }
}
