// <auto-generated />
using System;
using LY.LlmPool.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LY.LlmPool.Web.Data.Migrations
{
    [DbContext(typeof(LlmDbContext))]
    [Migration("20251011065005_AddPromptToolTable")]
    partial class AddPromptToolTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.AgentMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LlmAppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LlmConfigId")
                        .HasColumnType("text");

                    b.Property<string>("LlmPromptId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LlmAppId");

                    b.HasIndex("LlmConfigId");

                    b.HasIndex("LlmPromptId");

                    b.ToTable("AgentMembers");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long?>("CompletionTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<string>("LlmConfigId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModelCallStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModelResponseEndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModelResponseStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentCallId")
                        .HasColumnType("text");

                    b.Property<long?>("PromptTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestDataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("RequestReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ResponseDataJson")
                        .HasColumnType("jsonb");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("WaitTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("LlmConfigId");

                    b.HasIndex("ParentCallId");

                    b.HasIndex("RequestReceivedAt");

                    b.ToTable("EndpointCallRecords");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AppType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_type");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("EndpointId")
                        .HasColumnType("text")
                        .HasColumnName("endpoint_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LlmConfigId")
                        .HasColumnType("text")
                        .HasColumnName("llm_config_id");

                    b.Property<string>("LlmPromptId")
                        .HasColumnType("text")
                        .HasColumnName("llm_prompt_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("OrchestrationMode")
                        .HasColumnType("text")
                        .HasColumnName("orchestration_mode");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("LlmConfigId");

                    b.HasIndex("LlmPromptId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("llm_apps");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AdditionalHeadersJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("AdditionalParameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_parameters");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModelTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpoint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpointConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LlmConfigId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LlmConfigId");

                    b.HasIndex("EndpointId", "LlmConfigId")
                        .IsUnique();

                    b.ToTable("EndpointConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmModelType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultEndpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModelTypes");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmPrompt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ModelParameters")
                        .HasColumnType("text")
                        .HasColumnName("model_parameters");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("llm_prompts");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmPromptHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int?>("BasedOnVersion")
                        .HasColumnType("integer")
                        .HasColumnName("based_on_version");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModelParameters")
                        .HasColumnType("text")
                        .HasColumnName("model_parameters");

                    b.Property<string>("PromptId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_id");

                    b.Property<string>("TestConfigsJson")
                        .HasColumnType("text")
                        .HasColumnName("test_configs");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime");

                    b.HasIndex("PromptId");

                    b.ToTable("llm_prompt_history");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.McpServerConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Args")
                        .HasColumnType("text");

                    b.Property<string>("Command")
                        .HasColumnType("text");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Env")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemaCacheJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("McpServerConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.PromptTool", b =>
                {
                    b.Property<string>("PromptId")
                        .HasColumnType("text")
                        .HasColumnName("prompt_id");

                    b.Property<string>("ToolId")
                        .HasColumnType("text")
                        .HasColumnName("tool_id");

                    b.Property<string>("ToolType")
                        .HasColumnType("text")
                        .HasColumnName("tool_type");

                    b.HasKey("PromptId", "ToolId", "ToolType");

                    b.ToTable("prompt_tools");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.AgentMember", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmApp", "LlmApp")
                        .WithMany("AgentMembers")
                        .HasForeignKey("LlmAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmConfig", "LlmConfig")
                        .WithMany()
                        .HasForeignKey("LlmConfigId");

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmPrompt", "LlmPrompt")
                        .WithMany()
                        .HasForeignKey("LlmPromptId");

                    b.Navigation("LlmApp");

                    b.Navigation("LlmConfig");

                    b.Navigation("LlmPrompt");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmEndpoint", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmConfig", "LlmConfig")
                        .WithMany()
                        .HasForeignKey("LlmConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", "ParentCall")
                        .WithMany("ChildCalls")
                        .HasForeignKey("ParentCallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Endpoint");

                    b.Navigation("LlmConfig");

                    b.Navigation("ParentCall");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmApp", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmEndpoint", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId");

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmConfig", "LlmConfig")
                        .WithMany()
                        .HasForeignKey("LlmConfigId");

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmPrompt", "LlmPrompt")
                        .WithMany()
                        .HasForeignKey("LlmPromptId");

                    b.Navigation("Endpoint");

                    b.Navigation("LlmConfig");

                    b.Navigation("LlmPrompt");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmConfig", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmModelType", "ModelType")
                        .WithMany("Configs")
                        .HasForeignKey("ModelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelType");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpointConfig", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmEndpoint", "Endpoint")
                        .WithMany("EndpointConfigs")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmConfig", "LlmConfig")
                        .WithMany("EndpointConfigs")
                        .HasForeignKey("LlmConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");

                    b.Navigation("LlmConfig");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmPromptHistory", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmPrompt", "Prompt")
                        .WithMany()
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.PromptTool", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmPrompt", "Prompt")
                        .WithMany("PromptTools")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", b =>
                {
                    b.Navigation("ChildCalls");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmApp", b =>
                {
                    b.Navigation("AgentMembers");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmConfig", b =>
                {
                    b.Navigation("EndpointConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpoint", b =>
                {
                    b.Navigation("EndpointConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmModelType", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmPrompt", b =>
                {
                    b.Navigation("PromptTools");
                });
#pragma warning restore 612, 618
        }
    }
}
