// <auto-generated />
using System;
using LY.LlmPool.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LY.LlmPool.Web.Data.Migrations
{
    [DbContext(typeof(LlmDbContext))]
    [Migration("20250516040503_RemoveLlmConfigId1Shadow")]
    partial class RemoveLlmConfigId1Shadow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long?>("CompletionTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<string>("LlmConfigId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModelCallStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModelResponseEndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModelResponseStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentCallId")
                        .HasColumnType("text");

                    b.Property<long?>("PromptTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestDataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("RequestReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ResponseDataJson")
                        .HasColumnType("jsonb");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("WaitTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("LlmConfigId");

                    b.HasIndex("ParentCallId");

                    b.HasIndex("RequestReceivedAt");

                    b.ToTable("EndpointCallRecords");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AdditionalHeadersJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModelTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpoint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpointConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LlmConfigId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LlmConfigId");

                    b.HasIndex("EndpointId", "LlmConfigId")
                        .IsUnique();

                    b.ToTable("EndpointConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmModelType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultEndpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModelTypes");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmEndpoint", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmConfig", "LlmConfig")
                        .WithMany()
                        .HasForeignKey("LlmConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", "ParentCall")
                        .WithMany("ChildCalls")
                        .HasForeignKey("ParentCallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Endpoint");

                    b.Navigation("LlmConfig");

                    b.Navigation("ParentCall");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmConfig", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmModelType", "ModelType")
                        .WithMany("Configs")
                        .HasForeignKey("ModelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelType");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpointConfig", b =>
                {
                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmEndpoint", "Endpoint")
                        .WithMany("EndpointConfigs")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LY.LlmPool.Web.Data.Entities.LlmConfig", "LlmConfig")
                        .WithMany("EndpointConfigs")
                        .HasForeignKey("LlmConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");

                    b.Navigation("LlmConfig");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.EndpointCallRecord", b =>
                {
                    b.Navigation("ChildCalls");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmConfig", b =>
                {
                    b.Navigation("EndpointConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmEndpoint", b =>
                {
                    b.Navigation("EndpointConfigs");
                });

            modelBuilder.Entity("LY.LlmPool.Web.Data.Entities.LlmModelType", b =>
                {
                    b.Navigation("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
